* corrected bd

diff --git a/zcu106/Makefile b/zcu106/Makefile
--- a/zcu106/Makefile
+++ b/zcu106/Makefile
@@ -23,6 +23,7 @@ PFM_XPFM = $(PFM_DIR)/xilinx_$(PFM)_$(PFM_VER)/$(PFM).xpfm
 VITIS_DIR = overlays/examples
 VITIS_OVERLAY_DIR = $(VITIS_DIR)/$(OVERLAY)
 VITIS_OVERLAY_BIT = $(VITIS_OVERLAY_DIR)/binary_container_1/link/int/system.bit
+VITIS_OVERLAY_XCLBIN = $(VITIS_OVERLAY_DIR)/binary_container_1/dpu.xclbin
 
 # the PAC dir
 PAC_NAME = custom_pac
@@ -110,6 +111,44 @@ $(PAC_ZIP):
 	echo 'Create Platform Asset Container $(PFM)'; \
 	mkdir -p $(PAC_SUBDIR)
 	cp $(PETALINUX_IMAGES)/system.bit $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/system.dtb $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/bl31.elf $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/pmufw.elf $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/zynqmp_fsbl.elf $(PAC_SUBDIR)/.
+	@echo 'name: $(PF_NAME)' > $(PAC_MANIFEST)
+	@echo 'description: Boot assets for custom platform' >> $(PAC_MANIFEST)
+	@echo 'revision: 1' >> $(PAC_MANIFEST)
+	@echo 'assets:' >> $(PAC_MANIFEST)
+	@echo '    zcu106: zcu106' >> $(PAC_MANIFEST)
+	@echo 'the_ROM_image:' > $(PAC_BOOTGEN)
+	@echo '{' >> $(PAC_BOOTGEN)
+	@echo '        [bootloader, destination_cpu=a53-0] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/zynqmp_fsbl.elf' >> $(PAC_BOOTGEN)
+	@echo '        [pmufw_image] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/pmufw.elf' >> $(PAC_BOOTGEN)
+	@echo '        [destination_device=pl] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.bit' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, exception_level=el-3, trustzone] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/bl31.elf' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, load=0x00100000] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.dtb' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, exception_level=el-2] /usr/lib/u-boot/xilinx_zynqmp_virt/u-boot.elf' >> $(PAC_BOOTGEN)
+	@echo '}' >> $(PAC_BOOTGEN)
+	cd $(PAC_ROOT) && zip -r $(PAC_ZIP) $(PAC_NAME)
+
+.PHONY: pac_overlay
+pac_overlay: $(PAC_ZIP)
+$(PAC_ZIP):
+	@valid=0; \
+	for o in $(OVERLAY_LIST); do \
+	  if [ "$$o" = "$(OVERLAY)" ]; then \
+	    valid=1; \
+	    break; \
+	  fi \
+	done; \
+	if [ "$$valid" -ne 1 ]; then \
+	  echo 'Invalid parameter OVERLAY=$(OVERLAY). Choose one of: $(OVERLAY_LIST)'; \
+	  exit 1; \
+	fi; \
+	echo 'Create Platform Asset Container $(OVERLAY)'; \
+	mkdir -p $(PAC_SUBDIR)
+	cp $(VITIS_OVERLAY_BIT) $(PAC_SUBDIR)/.
+	cp $(VITIS_OVERLAY_XCLBIN) $(PAC_SUBDIR)/.
 	cp $(PETALINUX_IMAGES)/system.dtb $(PAC_SUBDIR)/.
 	cp $(PETALINUX_IMAGES)/bl31.elf $(PAC_SUBDIR)/.
 	cp $(PETALINUX_IMAGES)/pmufw.elf $(PAC_SUBDIR)/.
