* corrected the DPU clocks and resets

diff --git a/zcu106/Makefile b/zcu106/Makefile
--- a/zcu106/Makefile
+++ b/zcu106/Makefile
@@ -26,8 +26,8 @@ VITIS_OVERLAY_BIT = $(VITIS_OVERLAY_DIR)/binary_container_1/link/int/system.bit
 VITIS_OVERLAY_XCLBIN = $(VITIS_OVERLAY_DIR)/binary_container_1/dpu.xclbin
 
 # the PAC dir
-PAC_NAME = custom_pac
-PF_NAME = custom_platform
+PAC_NAME = $(OVERLAY)_pac
+PF_NAME = $(OVERLAY)_platform
 PAC_STRUCT = hwconfig/cfg/zcu106
 PAC_ROOT = $(PWD)/pac
 PAC_DIR = $(PAC_ROOT)/$(PAC_NAME)
@@ -42,6 +42,9 @@ PETALINUX_IMAGES = $(PFM_DIR)/petalinux/$(PFM)/images/linux
 help:
 	@echo 'Usage:'
 	@echo ''
+	@echo '  make pac OVERLAY=<val>'
+	@echo '    Build the Platform Assets Container (PAC).'
+	@echo ''
 	@echo '  make overlay OVERLAY=<val>'
 	@echo '    Build the Vitis application overlay.'
 	@echo ''
@@ -50,15 +53,50 @@ help:
 	@echo '  make platform PFM=<val> JOBS=<n>'
 	@echo '    Build the Vitis platform.'
 	@echo ''
-	@echo '  make pac PFM=<val>'
-	@echo '    Build the Platform Assets Container (PAC).'
-	@echo ''
 	@echo '    Valid options for PFM: ${PFM_LIST}'
 	@echo '    JOBS: optional param to set number of synthesis jobs (default 8)'
 	@echo ''
 	@echo '  make clean'
 	@echo '    Clean runs'
 	@echo ''
+
+.PHONY: pac
+pac: $(PAC_ZIP)
+$(PAC_ZIP): $(VITIS_OVERLAY_BIT)
+	@valid=0; \
+	for o in $(OVERLAY_LIST); do \
+	  if [ "$$o" = "$(OVERLAY)" ]; then \
+	    valid=1; \
+	    break; \
+	  fi \
+	done; \
+	if [ "$$valid" -ne 1 ]; then \
+	  echo 'Invalid parameter OVERLAY=$(OVERLAY). Choose one of: $(OVERLAY_LIST)'; \
+	  exit 1; \
+	fi; \
+	echo 'Create Platform Asset Container $(OVERLAY)'; \
+	mkdir -p $(PAC_SUBDIR)
+	cp $(VITIS_OVERLAY_BIT) $(PAC_SUBDIR)/.
+	cp $(VITIS_OVERLAY_XCLBIN) $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/system.dtb $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/bl31.elf $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/pmufw.elf $(PAC_SUBDIR)/.
+	cp $(PETALINUX_IMAGES)/zynqmp_fsbl.elf $(PAC_SUBDIR)/.
+	@echo 'name: $(PF_NAME)' > $(PAC_MANIFEST)
+	@echo 'description: Boot assets for $(OVERLAY) platform' >> $(PAC_MANIFEST)
+	@echo 'revision: 1' >> $(PAC_MANIFEST)
+	@echo 'assets:' >> $(PAC_MANIFEST)
+	@echo '    zcu106: zcu106' >> $(PAC_MANIFEST)
+	@echo 'the_ROM_image:' > $(PAC_BOOTGEN)
+	@echo '{' >> $(PAC_BOOTGEN)
+	@echo '        [bootloader, destination_cpu=a53-0] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/zynqmp_fsbl.elf' >> $(PAC_BOOTGEN)
+	@echo '        [pmufw_image] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/pmufw.elf' >> $(PAC_BOOTGEN)
+	@echo '        [destination_device=pl] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.bit' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, exception_level=el-3, trustzone] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/bl31.elf' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, load=0x00100000] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.dtb' >> $(PAC_BOOTGEN)
+	@echo '        [destination_cpu=a53-0, exception_level=el-2] /usr/lib/u-boot/xilinx_zynqmp_virt/u-boot.elf' >> $(PAC_BOOTGEN)
+	@echo '}' >> $(PAC_BOOTGEN)
+	cd $(PAC_ROOT) && zip -r $(PAC_ZIP) $(PAC_NAME)
 
 .PHONY: overlay
 overlay: $(VITIS_OVERLAY_BIT)
@@ -93,81 +131,6 @@ $(PFM_XPFM):
 	fi; \
 	echo 'Create Vitis platform $(PFM)'; \
 	$(MAKE) -C $(PFM_DIR) platform PLATFORM=$(PFM) VERSION=$(PFM_VER)
-
-.PHONY: pac
-pac: $(PAC_ZIP)
-$(PAC_ZIP):
-	@valid=0; \
-	for p in $(PFM_LIST); do \
-	  if [ "$$p" = "$(PFM)" ]; then \
-	    valid=1; \
-	    break; \
-	  fi \
-	done; \
-	if [ "$$valid" -ne 1 ]; then \
-	  echo 'Invalid parameter PFM=$(PFM). Choose one of: $(PFM_LIST)'; \
-	  exit 1; \
-	fi; \
-	echo 'Create Platform Asset Container $(PFM)'; \
-	mkdir -p $(PAC_SUBDIR)
-	cp $(PETALINUX_IMAGES)/system.bit $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/system.dtb $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/bl31.elf $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/pmufw.elf $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/zynqmp_fsbl.elf $(PAC_SUBDIR)/.
-	@echo 'name: $(PF_NAME)' > $(PAC_MANIFEST)
-	@echo 'description: Boot assets for custom platform' >> $(PAC_MANIFEST)
-	@echo 'revision: 1' >> $(PAC_MANIFEST)
-	@echo 'assets:' >> $(PAC_MANIFEST)
-	@echo '    zcu106: zcu106' >> $(PAC_MANIFEST)
-	@echo 'the_ROM_image:' > $(PAC_BOOTGEN)
-	@echo '{' >> $(PAC_BOOTGEN)
-	@echo '        [bootloader, destination_cpu=a53-0] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/zynqmp_fsbl.elf' >> $(PAC_BOOTGEN)
-	@echo '        [pmufw_image] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/pmufw.elf' >> $(PAC_BOOTGEN)
-	@echo '        [destination_device=pl] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.bit' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, exception_level=el-3, trustzone] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/bl31.elf' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, load=0x00100000] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.dtb' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, exception_level=el-2] /usr/lib/u-boot/xilinx_zynqmp_virt/u-boot.elf' >> $(PAC_BOOTGEN)
-	@echo '}' >> $(PAC_BOOTGEN)
-	cd $(PAC_ROOT) && zip -r $(PAC_ZIP) $(PAC_NAME)
-
-.PHONY: pac_overlay
-pac_overlay: $(PAC_ZIP)
-$(PAC_ZIP):
-	@valid=0; \
-	for o in $(OVERLAY_LIST); do \
-	  if [ "$$o" = "$(OVERLAY)" ]; then \
-	    valid=1; \
-	    break; \
-	  fi \
-	done; \
-	if [ "$$valid" -ne 1 ]; then \
-	  echo 'Invalid parameter OVERLAY=$(OVERLAY). Choose one of: $(OVERLAY_LIST)'; \
-	  exit 1; \
-	fi; \
-	echo 'Create Platform Asset Container $(OVERLAY)'; \
-	mkdir -p $(PAC_SUBDIR)
-	cp $(VITIS_OVERLAY_BIT) $(PAC_SUBDIR)/.
-	cp $(VITIS_OVERLAY_XCLBIN) $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/system.dtb $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/bl31.elf $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/pmufw.elf $(PAC_SUBDIR)/.
-	cp $(PETALINUX_IMAGES)/zynqmp_fsbl.elf $(PAC_SUBDIR)/.
-	@echo 'name: $(PF_NAME)' > $(PAC_MANIFEST)
-	@echo 'description: Boot assets for custom platform' >> $(PAC_MANIFEST)
-	@echo 'revision: 1' >> $(PAC_MANIFEST)
-	@echo 'assets:' >> $(PAC_MANIFEST)
-	@echo '    zcu106: zcu106' >> $(PAC_MANIFEST)
-	@echo 'the_ROM_image:' > $(PAC_BOOTGEN)
-	@echo '{' >> $(PAC_BOOTGEN)
-	@echo '        [bootloader, destination_cpu=a53-0] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/zynqmp_fsbl.elf' >> $(PAC_BOOTGEN)
-	@echo '        [pmufw_image] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/pmufw.elf' >> $(PAC_BOOTGEN)
-	@echo '        [destination_device=pl] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.bit' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, exception_level=el-3, trustzone] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/bl31.elf' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, load=0x00100000] /usr/local/share/xlnx-config/$(PAC_NAME)/$(PAC_STRUCT)/system.dtb' >> $(PAC_BOOTGEN)
-	@echo '        [destination_cpu=a53-0, exception_level=el-2] /usr/lib/u-boot/xilinx_zynqmp_virt/u-boot.elf' >> $(PAC_BOOTGEN)
-	@echo '}' >> $(PAC_BOOTGEN)
-	cd $(PAC_ROOT) && zip -r $(PAC_ZIP) $(PAC_NAME)
 
 .PHONY: clean
 clean:
